name: learn_buddy_project
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.9
  cupertino_icons: ^1.0.8
  http: ^1.2.2 # Combined from dev1_dependencies
  url_launcher: ^6.3.1
  my_line_awesome_icons: ^1.1.0
#  url_launcher: ^6.3.1

  firebase_core: ^2.26.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.16.1
#  google_sign_in: ^5.4.2
  firebase_storage: ^11.7.1
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/logo/lb_logo_pic.svg

  # Uncomment and add your custom fonts here, for example:
  fonts:
     - family: SixtyFour
       fonts:
         - asset: assets/fonts/Poppins-Medium.ttf

